services:
  - type: web
    name: pronunciation-quiz-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_app.backend.api.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: "true"
    routes:
      - path: "/"
        dest: "/"

  - type: web
    name: pronunciation-quiz-frontend
    env: static
    plan: free
    publishPath: web_app/frontend
    routes:
      - path: "/templates/*"
        dest: "/"
      - path: "/"
        dest: "index.html"
